---
name: Test `tailscale-runner-action`

on:
  pull_request:
    branches:
      - main

jobs:
  create-runners:
    name: Create self-hosted Actions runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        runner-name: [
          test
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
      - name: Create runner
        uses: ./
        with:
          gh-app-id: ${{ secrets.GH_APP_ID }}
          gh-app-login: MattKobayashi
          gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          runner-network: binarylane
          ssh-host: 100.69.53.59
          ssh-user: matthew
          ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          ts-tag: ci
  build-test:
    name: Test self-hosted Actions runner
    runs-on: self-hosted
    needs: [create-runners]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [
          test
        ]
    steps:
      - name: Tell the time
        run: |
          set -eux
          date
